version: '3.8'
services:
  discord-bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    env_file:
      - .env